---
apiVersion: v1
kind: Pod
metadata:
    name: mysql-pod
    namespace: sqldb
    #labels:
      #app.kubernetes.io/name: mysql
      #app.kubernetes.io/component: backend
spec:
    containers:
    - name: mysql-container
      image: 209830628404.dkr.ecr.us-east-1.amazonaws.com/clo835_week_09_assignment_02_db:v1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "db_clo835"
    imagePullSecrets:
      - name: regcred-mysql