---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
  namespace: app-employees
  labels:
    app.kubernetes.io/name: app-employees
    app.kubernetes.io/component: frontend
spec:
  #type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30001
  selector:
    app.kubernetes.io/name: app-employees
