---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v1
  namespace: webapp
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app.kubernetes.io/name: webapp
