---
apiVersion: v1
kind: Pod
metadata:
    name: webapp-pod
    namespace: webapp
    #labels:
      #app.kubernetes.io/name: webapp
spec:
    containers:
    - name: webapp-container
      image: 209830628404.dkr.ecr.us-east-1.amazonaws.com/clo835_week_09_assignment_02_app:v1.0
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "10.244.0.26"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "db_clo835"
    imagePullSecrets:
      - name: regcred-webapp